bases:
  - ../../base
patchesStrategicMerge:
  - database-connection-sealed-secret.yaml
  - database-migration-connection-sealed-secret.yaml
  - mapping.yaml
images:
- name: greenstand/treetracker-contract-api
  newTag: 0.0.1