apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-wait-for
  namespace: treetracker-contract-api
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
subjects:
  - kind: ServiceAccount
    name: default
    namespace: treetracker-contract-api
roleRef:
  kind: ClusterRole
  name: k8s-wait-for
  apiGroup: rbac.authorization.k8s.io
